### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by jm-riley** [jmsteen/austana#1]
### `projects`
- [x] is `layout` something that is stored in the database, or is it just a ui issue that can be dealt with on the frontend?
- [x] is `current_status` something that a user is required to fill out when they initially create a project? if not, either make it optional or set a default value
- [x] add indices to all foreign keys and specify which table they reference

### `tasks`
- [x] add indices to all foreign keys and specify which table they reference
- [x] `completed_at` should not have null constraint

### `users`
- [x] add `session_token`, `password_digest`, and `timestamps`
- [x] add index to `session_token`

### `task_lists`
- [x] add indices to all foreign keys and specify which table they reference

### `comments`
- [x] add indices to all foreign keys and specify which table they reference

It's looking great, nice work!

**Comment by jmsteen** [comment]
Can we use a column as a foreign key if it's optional (e.g. 'parent_task_id' in tasks)?

**Comment by jm-riley** [comment]
Yep! Just remember that rails adds default presence validations for any belongs_to association, so we have to specify "optional: true" when we set up the association in our models
